config/routes.rb
Glasbox::Application.routes.draw do
  get "admin/members"
  get "admin/events"
  get "pages/home"
  get "pages/about"
  get "pages/membership"

  resources :events
  resources :members
  resources :user_sessions
  
  resources :users do
    resource :membership
  end
  
  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as =>:logout
  match 'signup' => "users#new", :as => :signup

  match 'about' => "pages#about", :as => :about
  match 'membership' => "pages#membership", :as => :membership

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  get "admin/events", :as => :events_admin_path
  get "admin/members", :as => :member_admin_path
  get "admin/dashboard", :as => :dashboard

  root :to => 'pages#home'

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  attr_accessible :email, :user_id, :plan_id, :stripe_card_token
  attr_accessor	:stripe_card_token, :name, :address_line1, :address_zip
  
  before_save :update_stripe

  belongs_to :user

  validates_presence_of :plan_id
  validates_presence_of :email

  def update_stripe

    if stripe_customer_token.nil?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token, email: email, 
        name: name, address_line1: address_line1, address_zip: address_zip)
    else

      customer = Stripe::Customer.retrieve(stripe_customer_token)
      
      if stripe_card_token.present?
        customer.card = stripe_card_token
      end

      customer.plan = plan_id
      customer.email = email
      customer.save
    end

    self.stripe_customer_token = customer.id
    self.stripe_card_token = nil
  
  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while creating customer: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
    false
  end

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_filter :require_user
  before_filter :get_user
  before_filter :redirect_if_member, :only => :new

  def get_user
    @user = User.find(params[:user_id])
  end

  def index
    @memberships = Membership.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @memberships }
    end
  end


  def show
    @membership = @user.membership

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @membership }
    end
  end


  def new
    @membership = Membership.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @membership }
    end
  end


  def edit
    @membership = @user.membership

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @membership }
    end
  end


  def create
    @membership = Membership.new(params[:membership])

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @user, notice: 'Thank you for becoming a member!' }
        format.json { render json: @membership, status: :created, location: @membership }
      else
        format.html { render action: "new" }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @membership = @user.membership

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @user, notice: 'Membership was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to memberships_url }
      format.json { head :no_content }
    end
  end

  def redirect_if_member
    if @user.membership
     redirect_to @user, :notice => "You already have a membership." 
    end
  end

end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for([@user, @membership], :url => user_membership_path, :html => {:multipart => true, :class => 'form-horizontal membership_form' }) do 
  |f| %>
    <% if @membership.errors.any? %>
      <div class="alert alert-error alert-block">
        <h4>Woah There Were Some Errors!</h4>
        <ul>
          <% @membership.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %> 
    <%= f.hidden_field :email, :value => @user.email %>
    <%= f.hidden_field :user_id, :value => @user.id %> 
    <%= f.hidden_field :stripe_card_token, :id => "membership_stripe_card_token" %>

    <div class="alert alert-error" id="stripe_error">
      <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
    </div>

      <div class="control-group">
        <%= f.label :plan_id, "Choose your Plan", :class => 'control-label' %>
        <div class="controls">
          <%= f.select :plan_id, [['$60 for 6 Months', 1], ['$100 for 1 year', 2]] %>
        </div>
      </div>


      <% if @membership.stripe_customer_token.present? %>
        <div class="credit_card_prompt">
          Credit card has been provided. <%= link_to "Change Credit Card", "#", :id => "update_credit_card" %>
        </div>
        <div class="credit_card_inputs">
      <% end %>
        <div class="control-group ">
          <%= label_tag :name, "Name", :class => 'control-label' %>
          <div class="controls">
            <%= text_field_tag :name, @user.full_name, name: nil%>
          </div>
        </div>

          <div class="control-group ">
            <%= label_tag :address_line1, "Address", :class => 'control-label' %>
            <div class="controls">
              <%= text_field_tag :address_line1, nil, name: nil%>
            </div>
          </div>

          <div class="control-group ">
            <%= label_tag :address_zip, "Zip Code", :class => 'control-label' %>
            <div class="controls">
              <%= text_field_tag :address_zip, nil, name: nil%>
            </div>
          </div>

          <div class="control-group">
            <%= label_tag :card_number, "Credit Card Number", :class => 'control-label' %>
            <div class="controls">
              <%= text_field_tag :card_number, nil, name: nil, :id=>"card_number" %>
              <div class="cards">
                <%= image_tag "Visa.png" %>
                <%= image_tag "MasterCard.png" %>
                <%= image_tag "American Express.png" %>
                <%= image_tag "Discover.png" %>
              </div>
            </div>
          </div>

          <div class="control-group ">
            <%= label_tag :card_code, "Security Code on Card (CVV)", :class => 'control-label' %>
            <div class="controls">
              <%= text_field_tag :card_code, nil, name: nil, :id => "card_code" %>
              <div class="card_back">
                <%= image_tag 'back_card.png' %>
              </div>
            </div>
          </div>
          <div class="control-group">
            <%= label_tag :card_month, "Card Expiration", :class => 'control-label' %>
            <div class="controls">
              <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"} %>
              <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
            </div>
          </div>
        <% if @membership.stripe_customer_token.present? %>
          </div><!-- end credit_card_inputs -->
        <% end %>



  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary btn-large', :disable_with => "Loading..." %>
  </div>
<% end %>

<script>
  $('#update_credit_card').click(function(){
    $('.credit_card_prompt').fadeOut('fast');
    $('.credit_card_inputs').slideDown('slow');
  });
</script>

app/views/memberships/edit.html.erb
<section class="new_membership edit_membership">
	<h2 class="title"> Edit Membership </h2>
	<%= render :partial => 'form' %>
</section>

app/views/memberships/index.html.erb
<%- model_class = Membership -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= link_to membership.id, membership_path(membership) %></td>
        <td><%= membership.email %></td>
        <td><%=l membership.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_membership_path(membership), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      membership_path(membership),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/memberships/new.html.erb
<section class="new_membership">
	<h2 class="title"> One Step away from signing up to Glasbox Membership </h2>
	<p class="gray">
	Pellentesque felis ligula, convallis consectetur facilisis mattis, accumsan eu lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris quis hendrerit dolor. Nulla facilisi. Aliquam bibendum dictum sem vitae aliquam. Nulla vel tincidunt erat. Donec ut nulla ante, et dapibus mi. Vivamus convallis tincidunt metus, vel ultrices velit aliquam non. Donec cursus justo eget elit luctus imperdiet.
	</p>

	<%= render :partial => 'form' %>
</section>

app/views/memberships/show.html.erb
<section class="membership_show">
  <h3 class="title"> <b>Glasbox</b> is a facility that manufactures creative opportunities
  </h3>
  <%- model_class = Membership -%>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human %></h1>
  </div>

  <dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
    <dd><%= @membership.email %></dd>
  </dl>
</section>