config/routes.rb
Glasbox::Application.routes.draw do
  get "admin/members"
  get "admin/events"
  get "pages/home"
  get "pages/about"
  get "pages/membership"

  resources :events
  resources :members
  resources :user_sessions
  
  resources :users do
    resource :membership
  end
  
  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as =>:logout
  match 'signup' => "users#new", :as => :signup

  match 'about' => "pages#about", :as => :about
  match 'membership' => "pages#membership", :as => :membership

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  get "admin/events", :as => :events_admin_path
  get "admin/members", :as => :member_admin_path
  get "admin/dashboard", :as => :dashboard

  root :to => 'pages#home'

end

app/views/admin/dashboard.html.erb
<section class="admin content clearfix">
	<h2>Admin Dashboard</h2>

	<!-- Users -->
	<div class="well span3">
		<h4> <i class="icon-user icon-large"></i> Users </h4>
		<p> Manage Users: Users willl be able to access the admin dashboard
			and will be able to manage all admin functions. 
		</p>
		<div class="btn-group">
			<%= link_to "Users", users_path, :class => "btn span12  btn-primary" %>

		  <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
		    <span class="caret"></span>
		  </button>
		  <ul class="dropdown-menu">
		    <li><%= link_to 'Users', users_path %></li>
		    <li><%= link_to 'Add a User', new_user_path %></li>
		  </ul>
		</div>
	</div>

	<!-- Events -->
	<div class="well span3">
		<h4> <i class="icon-home icon-large"></i> Events </h4>
		<p> Manage Properties: Properties are what visitors to the site
			will want to come and see. Make sure you add properties often.
		</p>
		<div class="btn-group">
			<%= link_to "Events", :events_admin_path, :class => "btn span12  btn-primary" %>

		  <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
		    <span class="caret"></span>
		  </button>
		  <ul class="dropdown-menu ">
		    <li><%= link_to 'Events', :events_admin_path %></li>
		    <li><%= link_to 'Add an Event', new_event_path %></li>
		  </ul>
		</div>
	</div>

	<!-- Members -->
	<div class="well span3">
		<h4> <i class="icon-comment-alt icon-large"></i> Members </h4>
		<p> Manage Members: Members about your company is important to establish 
			the legitimacy of your website to visitors and search engins. Make
			sure to add news often. 
		</p>
		<div class="btn-group">
			<%= link_to "Members", :member_admin_path, :class => "btn span12  btn-primary" %>

		  <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
		    <span class="caret"></span>
		  </button>
		  <ul class="dropdown-menu ">
		    <li><%= link_to 'List Members', :member_admin_path %></li>
		    <li><%= link_to 'New Member', new_member_path %></li>
		  </ul>
		</div>
	</div>
</section>

app/views/admin/events.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.id, event_path(event) %></td>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%=l event.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_event_path,
            :class => 'btn btn-primary' %>

app/views/admin/members.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.id, member_path(member) %></td>
        <td><%= member.name %></td>
        <td><%= member.description %></td>
        <td><%=l member.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_member_path(member), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      member_path(member),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_member_path,
            :class => 'btn btn-primary' %>