config/routes.rb
Glasbox::Application.routes.draw do
  get "admin/members"
  get "admin/events"
  get "pages/home"
  get "pages/about"
  get "pages/membership"

  resources :events
  resources :members
  resources :user_sessions
  
  resources :users do
    resource :membership
  end
  
  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as =>:logout
  match 'signup' => "users#new", :as => :signup

  match 'about' => "pages#about", :as => :about
  match 'membership' => "pages#membership", :as => :membership

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  get "admin/events", :as => :events_admin_path
  get "admin/members", :as => :member_admin_path
  get "admin/dashboard", :as => :dashboard

  root :to => 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  #Attributes
  attr_accessible :email, :first_name, :last_name, 
  				  :password, :password_confirmation, :is_admin

  	has_one :membership

	#Authlogic
	acts_as_authentic do |c|
		c.login_field = :email
	end

	#Defs
	def full_name
	  "#{first_name} #{last_name}"
	end 

	def stripe_customer
		Stripe::Customer.retrieve(self.membership.stripe_customer_token)
	end

	def membership_type
		if membership.plan_id == 1
			"Friend"
		elsif membership.plan_id == 2
			"Gold"
		else
			"Free"
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @membership = @user.membership

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, "First Name", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, "Last Name", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :class => 'text_field' %>
    </div>
  </div>


  <div class="control-group">
    <%= f.label :name, "Confirm Password", :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password_confirmation, :class => 'text_field' %>
    </div>
  </div>

    <%= f.submit "Sign Up", :class => 'btn btn-primary btn-large btn-block' %>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:crypted_password) %></th>
      <th><%= model_class.human_attribute_name(:password_salt) %></th>
      <th><%= model_class.human_attribute_name(:persistence_token) %></th>
      <th><%= model_class.human_attribute_name(:perishable_token) %></th>
      <th><%= model_class.human_attribute_name(:last_request_at) %></th>
      <th><%= model_class.human_attribute_name(:current_login_at) %></th>
      <th><%= model_class.human_attribute_name(:last_login_at) %></th>
      <th><%= model_class.human_attribute_name(:current_login_ip) %></th>
      <th><%= model_class.human_attribute_name(:last_login_ip) %></th>
      <th><%= model_class.human_attribute_name(:is_admin) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= user.password_salt %></td>
        <td><%= user.persistence_token %></td>
        <td><%= user.perishable_token %></td>
        <td><%= user.last_request_at %></td>
        <td><%= user.current_login_at %></td>
        <td><%= user.last_login_at %></td>
        <td><%= user.current_login_ip %></td>
        <td><%= user.last_login_ip %></td>
        <td><%= user.is_admin %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<section class="signup">
	<div class="signup_form hero-unit">
		<h2 class="title">Sign Up</h2>
		<p>
		Quisque est diam, feugiat non consequat eu, fermentum a elit. Aenean lectus ligula, euismod id vestibulum nec, facilisis ut leo. Proin elit risus, egestas nec fringilla quis, vehicula at dui.
		</p>
		<%= render :partial => 'form' %>
	</div>
</section>

app/views/users/show.html.erb
<section class="user_account">
  <h2>Your Account</h2>
  <div class="well well-large">
    <% if @user.membership %>
      <% @customer = @user.stripe_customer %>
    	<% if @user.membership.plan_id == 1 %>
    		<h3>Friend Member</h3>
    		<p>Thank you for being a payed member of Glasbox.</p>
      <% elsif @user.membership.plan_id == 2 %>
      	<h3>Gold Member</h3>
      	<p>Thank you for being a payed member of Glasbox.</p>
      <% end %>
    <% else %>
    	<h3>Free Member</h3>
    	You are on a free memberhip plan. View the advantages of being a paid member.<br/><br/>
    	<%= link_to 'View Membership Plans', 'memberships', :class => "btn btn-primary" %>
	<% end %>
  </div>

  <div class="row-fluid">
  	<div class="span6">
  		<h4>Account</h4>
  		<p><%= @user.full_name %></p>
  		<p><%= @user.email %></p>

  		<%= link_to "Edit My Account Information", edit_user_path(@user), :class => "btn btn-primary" %>
  	</div>

  	<div class="span6">
  		<h4>Membership</h4>
      <% if @user.membership %>
    		<p>Membership Type: <%= @user.membership_type %></p>
    		<p>Card Used: ************<%= @customer.active_card.last4 %> <%= image_tag "#{@customer.active_card.type}.png" %></p>
    		
    		<%= link_to "Edit My Membership Information", "/users/#{@user.id}/membership/edit", :class => "btn btn-primary" %>
      <% else %>
        <p>Membership Type: Free Member</p>
        <%= link_to "Upgrade Membership", new_user_membership_path(@user), :class => "btn btn-primary" %>
      <% end %>
  	</div>
  </div>
  
  
</section>