config/routes.rb
Glasbox::Application.routes.draw do
  get "admin/members"
  get "admin/events"
  get "pages/home"
  get "pages/about"
  get "pages/membership"

  resources :events
  resources :members
  resources :user_sessions
  
  resources :users do
    resource :membership
  end
  
  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as =>:logout
  match 'signup' => "users#new", :as => :signup

  match 'about' => "pages#about", :as => :about
  match 'membership' => "pages#membership", :as => :membership

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  get "admin/events", :as => :events_admin_path
  get "admin/members", :as => :member_admin_path
  get "admin/dashboard", :as => :dashboard

  root :to => 'pages#home'

end

app/views/layouts/_admin_bar.html.erb
<!-- Start Admin Bar -->
<% if current_user %>
<% if current_user.is_admin %>
  <div class="admin_bar">
    <div class ="container">
      <div class="row">
        <div class="span12"> 
          <div class="user_actions"> 
            <div class="btn-group">
              <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                Hello <%= current_user.full_name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Admin Dashboard", '#' %></li>
                <li><%= link_to "Edit Profile", :logout, :tabindex => "-1" %></li>
                <li><%= link_to "Another Link", :logout, :tabindex => "-1" %></li>
                <li class="divider"></li>
                <li><%= link_to "Logout", :logout, :tabindex => "-1" %></li>
              </ul>
            </div>
          </div><!-- end user_actions -->

        </div> <!-- en span12 -->
      </div> <!-- end container -->
    </div> <!-- end container -->
  </div><!-- end admin_bar -->
<% end %><!-- End Admin Bar -->
<% end %>

app/views/layouts/_alerts.html.erb
<!-- Start Alerts -->
<div class="alerts">
  <% if flash[:alert] %>
    <div class="alert alert-error alert-block fade in temp_alert">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4>Oh Snap!</h4>
      <p><%= flash[:alert] %></p>
    </div>
  <% end %>

  <% if flash[:notice] %>
    <div class="alert alert-info alert-block fade in temp_alert">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4><%= flash[:notice] %></h4>
    </div>
  <% end %>

  <% if flash[:success] %>
    <div class="alert alert-success alert-block fade in temp_alert">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4>Success!</h4>
      <p><%= flash[:success] %></p>
    </div>
  <% end %>
</div><!-- End Alerts -->

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
	<h3 class="sidebar_header">Glasbox Newsletter</h3>
	<p class="sidebar_content">Join our newsletter and... 
		Etiam facilisis erat at turpis.</p>
	<div class="subscribe">
		<input placeholder="Email"> </input>
		<%= link_to "Subscribe", '', :class => "btn btn-primary" %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Glasbox - Manufacturing Creative Oppertunites - El Paso Texas</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <!-- Stripe -->
  <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Alert Close Automatically-->
  <script>
    $(function() {
        setTimeout(function() {
            $(".temp_alert").alert('close') 
          }, 5000);
    });
  </script>

</head>
<body>
  <%= render 'layouts/admin_bar' %>
  <%= render 'layouts/alerts' %>

  <header class="mainh"> 
    <div class="container">
      <div class="row-fluid">
        <div class="span12">
          <!-- Title Goes here -->
          <div class="logo"><%= link_to image_tag('logo.png'), :root %></div>

          <!-- Navigation -->
          <ul class="navigationm">
            <li class="navli"> <%= link_to 'Home', :root %></li>
            <li class="navli"> <%= link_to 'About', :about %></li>
            <li class="navli"> <%= link_to 'Members', members_path %></li>
            <li class="navli"> <%= link_to 'Membership', :membership %></li>
            <li class="navli"> <%= link_to 'Events', events_path %></li>
            <li class="navli"> <%= link_to 'Contact', 'contact' %></li>
          </ul>
        </div><!-- EDN SPAN12 -->
      </div><!--  END ROW -->
    </div><!-- END Containter -->
  </header>
 
  <div class="container">
    <div class="row-fluid">
      <div class="span6">
      </div>

      <div class="span6">
       
        <!-- News Letter -->
          <div class="sidebar_header">
            <p class="sidebar_content">Join our newsletter</p>
            <div class="subscribe">
              <input placeholder="Email"> </input>
              <%= link_to "Subscribe", '', :class => "btn btn-primary" %>
            </div>
          </div>
        <!-- News Letter Ends -->
        
        <div class="social-media">
          <p>
            You can follow us on the following social networks 
          </p>
          
          <ul>
            <li id="facebook"><%= link_to '', 'http://www.facebook.com/Glasbox' %></li>
          
          </ul>
        </div>
      </div><!-- end span6 -->
    </div> <!-- end row-fluid -->

    <div class="row-fluid">
      <div class="span12 main_content">
        <%= yield %>
      </div><!-- end main_content -->
    </div> <!-- end row-fluid -->


  </div><!-- end container -->
</body>
</html>